/*
 * Notebook Navigator - Plugin for Obsidian
 * Copyright (c) 2025-2026 Johan Sanneblad
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// Generated by scripts/build-languages.mjs. Do not edit.

export const LANGUAGE_DATA_ID = 'e7891acff0bbb121751304c5e538dbb16499640914af7b8d26671f240631b8c1';
export const LANGUAGE_METADATA = {
    ar: {
        dateFormat: 'D MMM YYYY',
        timeFormat: 'h:mm a',
        defaultVaultProfileName: 'افتراضي',
        bootstrap: {
            downloading: 'جارٍ تنزيل اللغات…',
            continueInEnglish: 'المتابعة بالإنجليزية',
            downloadFailed: 'تعذّر تنزيل اللغات. يستخدم Notebook Navigator اللغة الإنجليزية.'
        },
        formatters: {
            'paneHeader.applySortAndGroupToDescendants': (target: string) => `تطبيق الفرز والتجميع على ${target}`,
            'modals.bulkApply.applySortAndGroupTitle': (target: string) => `تطبيق الفرز والتجميع على ${target}؟`,
            'modals.bulkApply.affectedCountMessage': (count: number) => `التجاوزات الحالية التي ستتغير: ${count}.`,
            'modals.navRainbowSection.title': (section: string) => `ألوان قوس قزح: ${section}`,
            'modals.folderSuggest.placeholder': (name: string) => `نقل ${name} إلى مجلد...`,
            'modals.folderSuggest.multipleFilesLabel': (count: number) => `${count} من الملفات`
        }
    },
    de: {
        dateFormat: 'DD.MM.YYYY',
        timeFormat: 'HH:mm',
        defaultVaultProfileName: 'Standard',
        bootstrap: {
            downloading: 'Sprachen werden heruntergeladen…',
            continueInEnglish: 'Auf Englisch fortfahren',
            downloadFailed: 'Sprachdownload fehlgeschlagen. Notebook Navigator verwendet Englisch.'
        },
        formatters: {
            'paneHeader.applySortAndGroupToDescendants': (target: string) => `Sortierung und Gruppierung auf ${target} anwenden`,
            'modals.bulkApply.applySortAndGroupTitle': (target: string) => `Sortierung und Gruppierung auf ${target} anwenden?`,
            'modals.bulkApply.affectedCountMessage': (count: number) => `Vorhandene Überschreibungen, die sich ändern: ${count}.`,
            'modals.navRainbowSection.title': (section: string) => `Regenbogenfarben: ${section}`,
            'modals.folderSuggest.placeholder': (name: string) => `In Ordner verschieben: ${name}...`,
            'modals.folderSuggest.multipleFilesLabel': (count: number) => `${count} Dateien`
        }
    },
    en: {
        dateFormat: 'MMM D, YYYY',
        timeFormat: 'h:mm a',
        defaultVaultProfileName: 'Default',
        bootstrap: {
            downloading: 'Downloading languages…',
            continueInEnglish: 'Continue in English',
            downloadFailed: 'Language download failed. Notebook Navigator is using English.'
        },
        formatters: {
            'paneHeader.applySortAndGroupToDescendants': (target: string) => `Apply sort and group to ${target}`,
            'modals.bulkApply.applySortAndGroupTitle': (target: string) => `Apply sort and group to ${target}?`,
            'modals.bulkApply.affectedCountMessage': (count: number) => `Existing overrides that will change: ${count}.`,
            'modals.navRainbowSection.title': (section: string) => `Rainbow colors: ${section}`,
            'modals.folderSuggest.placeholder': (name: string) => `Move ${name} to folder...`,
            'modals.folderSuggest.multipleFilesLabel': (count: number) => `${count} files`
        }
    },
    es: {
        dateFormat: 'D [de] MMMM [de] YYYY',
        timeFormat: 'HH:mm',
        defaultVaultProfileName: 'Predeterminado',
        bootstrap: {
            downloading: 'Descargando idiomas…',
            continueInEnglish: 'Continuar en inglés',
            downloadFailed: 'No se pudieron descargar los idiomas. Notebook Navigator usa inglés.'
        },
        formatters: {
            'paneHeader.applySortAndGroupToDescendants': (target: string) => `Aplicar orden y agrupación a ${target}`,
            'modals.bulkApply.applySortAndGroupTitle': (target: string) => `¿Aplicar orden y agrupación a ${target}?`,
            'modals.bulkApply.affectedCountMessage': (count: number) => `Anulaciones existentes que cambiarán: ${count}.`,
            'modals.navRainbowSection.title': (section: string) => `Colores arcoíris: ${section}`,
            'modals.folderSuggest.placeholder': (name: string) => `Mover ${name} a carpeta...`,
            'modals.folderSuggest.multipleFilesLabel': (count: number) => `${count} archivos`
        }
    },
    fa: {
        dateFormat: 'YYYY/MM/DD',
        timeFormat: 'HH:mm',
        defaultVaultProfileName: 'پیش‌فرض',
        bootstrap: {
            downloading: 'در حال دانلود زبان‌ها…',
            continueInEnglish: 'ادامه به انگلیسی',
            downloadFailed: 'دانلود زبان‌ها ناموفق بود. Notebook Navigator از انگلیسی استفاده می‌کند.'
        },
        formatters: {
            'paneHeader.applySortAndGroupToDescendants': (target: string) => `اعمال مرتب‌سازی و گروه‌بندی به ${target}`,
            'modals.bulkApply.applySortAndGroupTitle': (target: string) => `مرتب‌سازی و گروه‌بندی به ${target} اعمال شود؟`,
            'modals.bulkApply.affectedCountMessage': (count: number) => `بازنویسی‌های موجود که تغییر خواهند کرد: ${count}.`,
            'modals.navRainbowSection.title': (section: string) => `رنگ‌های رنگین‌کمان: ${section}`,
            'modals.folderSuggest.placeholder': (name: string) => `انتقال ${name} به پوشه...`,
            'modals.folderSuggest.multipleFilesLabel': (count: number) => `${count} فایل`
        }
    },
    fr: {
        dateFormat: 'D MMMM YYYY',
        timeFormat: 'HH:mm',
        defaultVaultProfileName: 'Par défaut',
        bootstrap: {
            downloading: 'Téléchargement des langues…',
            continueInEnglish: 'Continuer en anglais',
            downloadFailed: 'Le téléchargement des langues a échoué. Notebook Navigator utilise l’anglais.'
        },
        formatters: {
            'paneHeader.applySortAndGroupToDescendants': (target: string) => `Appliquer le tri et le regroupement aux ${target}`,
            'modals.bulkApply.applySortAndGroupTitle': (target: string) => `Appliquer le tri et le regroupement aux ${target} ?`,
            'modals.bulkApply.affectedCountMessage': (count: number) => `Remplacements existants qui seront modifiés : ${count}.`,
            'modals.navRainbowSection.title': (section: string) => `Couleurs arc-en-ciel : ${section}`,
            'modals.folderSuggest.placeholder': (name: string) => `Déplacer ${name} vers le dossier...`,
            'modals.folderSuggest.multipleFilesLabel': (count: number) => `${count} fichiers`
        }
    },
    id: {
        dateFormat: 'D MMM YYYY',
        timeFormat: 'HH:mm',
        defaultVaultProfileName: 'Default',
        bootstrap: {
            downloading: 'Mengunduh bahasa…',
            continueInEnglish: 'Lanjutkan dalam bahasa Inggris',
            downloadFailed: 'Unduhan bahasa gagal. Notebook Navigator menggunakan bahasa Inggris.'
        },
        formatters: {
            'paneHeader.applySortAndGroupToDescendants': (target: string) => `Terapkan urutan dan grup ke ${target}`,
            'modals.bulkApply.applySortAndGroupTitle': (target: string) => `Terapkan urutan dan grup ke ${target}?`,
            'modals.bulkApply.affectedCountMessage': (count: number) => `Penimpaan yang ada dan akan berubah: ${count}.`,
            'modals.navRainbowSection.title': (section: string) => `Warna pelangi: ${section}`,
            'modals.folderSuggest.placeholder': (name: string) => `Pindahkan ${name} ke folder...`,
            'modals.folderSuggest.multipleFilesLabel': (count: number) => `${count} file`
        }
    },
    it: {
        dateFormat: 'D MMM YYYY',
        timeFormat: 'HH:mm',
        defaultVaultProfileName: 'Predefinito',
        bootstrap: {
            downloading: 'Download delle lingue…',
            continueInEnglish: 'Continua in inglese',
            downloadFailed: 'Download delle lingue non riuscito. Notebook Navigator usa l’inglese.'
        },
        formatters: {
            'paneHeader.applySortAndGroupToDescendants': (target: string) => `Applica ordinamento e raggruppamento a ${target}`,
            'modals.bulkApply.applySortAndGroupTitle': (target: string) => `Applicare ordinamento e raggruppamento a ${target}?`,
            'modals.bulkApply.affectedCountMessage': (count: number) => `Sostituzioni esistenti che cambieranno: ${count}.`,
            'modals.navRainbowSection.title': (section: string) => `Colori arcobaleno: ${section}`,
            'modals.folderSuggest.placeholder': (name: string) => `Sposta ${name} nella cartella...`,
            'modals.folderSuggest.multipleFilesLabel': (count: number) => `${count} file`
        }
    },
    ja: {
        dateFormat: 'YYYY年M月D日',
        timeFormat: 'HH:mm',
        defaultVaultProfileName: 'デフォルト',
        bootstrap: {
            downloading: '言語をダウンロード中…',
            continueInEnglish: '英語で続行',
            downloadFailed: '言語のダウンロードに失敗しました。Notebook Navigator は英語を使用しています。'
        },
        formatters: {
            'paneHeader.applySortAndGroupToDescendants': (target: string) => `${target}に並べ替えとグループ化を適用`,
            'modals.bulkApply.applySortAndGroupTitle': (target: string) => `${target}に並べ替えとグループ化を適用しますか？`,
            'modals.bulkApply.affectedCountMessage': (count: number) => `変更される既存のオーバーライド: ${count}。`,
            'modals.navRainbowSection.title': (section: string) => `レインボーカラー: ${section}`,
            'modals.folderSuggest.placeholder': (name: string) => `${name} をフォルダに移動...`,
            'modals.folderSuggest.multipleFilesLabel': (count: number) => `${count} 個のファイル`
        }
    },
    ko: {
        dateFormat: 'YYYY년 M월 D일',
        timeFormat: 'a h:mm',
        defaultVaultProfileName: '기본',
        bootstrap: {
            downloading: '언어 다운로드 중…',
            continueInEnglish: '영어로 계속',
            downloadFailed: '언어를 다운로드하지 못했습니다. Notebook Navigator가 영어를 사용합니다.'
        },
        formatters: {
            'paneHeader.applySortAndGroupToDescendants': (target: string) => `${target}에 정렬 및 그룹 적용`,
            'modals.bulkApply.applySortAndGroupTitle': (target: string) => `${target}에 정렬 및 그룹을 적용하시겠습니까?`,
            'modals.bulkApply.affectedCountMessage': (count: number) => `변경될 기존 재정의: ${count}.`,
            'modals.navRainbowSection.title': (section: string) => `무지개 색상: ${section}`,
            'modals.folderSuggest.placeholder': (name: string) => `${name}을(를) 폴더로 이동...`,
            'modals.folderSuggest.multipleFilesLabel': (count: number) => `${count}개의 파일`
        }
    },
    nl: {
        dateFormat: 'D MMM YYYY',
        timeFormat: 'HH:mm',
        defaultVaultProfileName: 'Standaard',
        bootstrap: {
            downloading: 'Talen downloaden…',
            continueInEnglish: 'Doorgaan in het Engels',
            downloadFailed: 'Talen downloaden mislukt. Notebook Navigator gebruikt Engels.'
        },
        formatters: {
            'paneHeader.applySortAndGroupToDescendants': (target: string) => `Sortering en groepering toepassen op ${target}`,
            'modals.bulkApply.applySortAndGroupTitle': (target: string) => `Sortering en groepering toepassen op ${target}?`,
            'modals.bulkApply.affectedCountMessage': (count: number) => `Bestaande overschrijvingen die wijzigen: ${count}.`,
            'modals.navRainbowSection.title': (section: string) => `Regenboogkleuren: ${section}`,
            'modals.folderSuggest.placeholder': (name: string) => `Verplaats ${name} naar map...`,
            'modals.folderSuggest.multipleFilesLabel': (count: number) => `${count} bestanden`
        }
    },
    pl: {
        dateFormat: 'DD.MM.YYYY',
        timeFormat: 'HH:mm',
        defaultVaultProfileName: 'Domyślny',
        bootstrap: {
            downloading: 'Pobieranie języków…',
            continueInEnglish: 'Kontynuuj po angielsku',
            downloadFailed: 'Nie udało się pobrać języków. Notebook Navigator używa języka angielskiego.'
        },
        formatters: {
            'paneHeader.applySortAndGroupToDescendants': (target: string) => `Zastosuj sortowanie i grupowanie dla ${target}`,
            'modals.bulkApply.applySortAndGroupTitle': (target: string) => `Zastosuj sortowanie i grupowanie dla ${target}?`,
            'modals.bulkApply.affectedCountMessage': (count: number) => `Istniejące nadpisania do zmiany: ${count}.`,
            'modals.navRainbowSection.title': (section: string) => `Kolory tęczy: ${section}`,
            'modals.folderSuggest.placeholder': (name: string) => `Przenieś ${name} do folderu...`,
            'modals.folderSuggest.multipleFilesLabel': (count: number) =>
                `${count} ${count === 1 ? 'plik' : count % 10 >= 2 && count % 10 <= 4 && (count % 100 < 12 || count % 100 > 14) ? 'pliki' : 'plików'}`
        }
    },
    pt: {
        dateFormat: 'D MMM YYYY',
        timeFormat: 'HH:mm',
        defaultVaultProfileName: 'Predefinido',
        bootstrap: {
            downloading: 'A transferir idiomas…',
            continueInEnglish: 'Continuar em inglês',
            downloadFailed: 'A transferência dos idiomas falhou. O Notebook Navigator está a usar inglês.'
        },
        formatters: {
            'paneHeader.applySortAndGroupToDescendants': (target: string) => `Aplicar ordenação e agrupamento a ${target}`,
            'modals.bulkApply.applySortAndGroupTitle': (target: string) => `Aplicar ordenação e agrupamento a ${target}?`,
            'modals.bulkApply.affectedCountMessage': (count: number) => `Substituições existentes que serão alteradas: ${count}.`,
            'modals.navRainbowSection.title': (section: string) => `Cores arco-íris: ${section}`,
            'modals.folderSuggest.placeholder': (name: string) => `Mover ${name} para pasta...`,
            'modals.folderSuggest.multipleFilesLabel': (count: number) => `${count} ficheiros`
        }
    },
    pt_br: {
        dateFormat: 'DD/MM/YYYY',
        timeFormat: 'HH:mm',
        defaultVaultProfileName: 'Padrão',
        bootstrap: {
            downloading: 'Baixando idiomas…',
            continueInEnglish: 'Continuar em inglês',
            downloadFailed: 'Não foi possível baixar os idiomas. O Notebook Navigator está usando inglês.'
        },
        formatters: {
            'paneHeader.applySortAndGroupToDescendants': (target: string) => `Aplicar classificação e agrupamento a ${target}`,
            'modals.bulkApply.applySortAndGroupTitle': (target: string) => `Aplicar classificação e agrupamento a ${target}?`,
            'modals.bulkApply.affectedCountMessage': (count: number) => `Substituições existentes que serão alteradas: ${count}.`,
            'modals.navRainbowSection.title': (section: string) => `Cores arco-íris: ${section}`,
            'modals.folderSuggest.placeholder': (name: string) => `Mover ${name} para pasta...`,
            'modals.folderSuggest.multipleFilesLabel': (count: number) => `${count} arquivos`
        }
    },
    ru: {
        dateFormat: 'D MMMM YYYY',
        timeFormat: 'HH:mm',
        defaultVaultProfileName: 'По умолчанию',
        bootstrap: {
            downloading: 'Загрузка языков…',
            continueInEnglish: 'Продолжить на английском',
            downloadFailed: 'Не удалось загрузить языки. Notebook Navigator использует английский.'
        },
        formatters: {
            'paneHeader.applySortAndGroupToDescendants': (target: string) => `Применить сортировку и группировку для ${target}`,
            'modals.bulkApply.applySortAndGroupTitle': (target: string) => `Применить сортировку и группировку для ${target}?`,
            'modals.bulkApply.affectedCountMessage': (count: number) => `Существующих переопределений, которые изменятся: ${count}.`,
            'modals.navRainbowSection.title': (section: string) => `Цвета радуги: ${section}`,
            'modals.folderSuggest.placeholder': (name: string) => `Переместить ${name} в папку...`,
            'modals.folderSuggest.multipleFilesLabel': (count: number) =>
                `${count} ${count % 10 === 1 && count % 100 !== 11 ? 'файл' : count % 10 >= 2 && count % 10 <= 4 && (count % 100 < 12 || count % 100 > 14) ? 'файла' : 'файлов'}`
        }
    },
    th: {
        dateFormat: 'D MMM YYYY',
        timeFormat: 'HH:mm',
        defaultVaultProfileName: 'ค่าเริ่มต้น',
        bootstrap: {
            downloading: 'กำลังดาวน์โหลดภาษา…',
            continueInEnglish: 'ดำเนินการต่อเป็นภาษาอังกฤษ',
            downloadFailed: 'ดาวน์โหลดภาษาไม่สำเร็จ Notebook Navigator กำลังใช้ภาษาอังกฤษ'
        },
        formatters: {
            'paneHeader.applySortAndGroupToDescendants': (target: string) => `ใช้การเรียงและการจัดกลุ่มกับ${target}`,
            'modals.bulkApply.applySortAndGroupTitle': (target: string) => `ใช้การเรียงและการจัดกลุ่มกับ${target}?`,
            'modals.bulkApply.affectedCountMessage': (count: number) => `การแทนที่ที่มีอยู่ซึ่งจะเปลี่ยนแปลง: ${count}`,
            'modals.navRainbowSection.title': (section: string) => `สีรุ้ง: ${section}`,
            'modals.folderSuggest.placeholder': (name: string) => `ย้าย ${name} ไปยังโฟลเดอร์...`,
            'modals.folderSuggest.multipleFilesLabel': (count: number) => `${count} ไฟล์`
        }
    },
    tr: {
        dateFormat: 'D MMM YYYY',
        timeFormat: 'HH:mm',
        defaultVaultProfileName: 'Varsayılan',
        bootstrap: {
            downloading: 'Diller indiriliyor…',
            continueInEnglish: 'İngilizce devam et',
            downloadFailed: 'Diller indirilemedi. Notebook Navigator İngilizce kullanıyor.'
        },
        formatters: {
            'paneHeader.applySortAndGroupToDescendants': (target: string) => `Sıralama ve gruplandırmayı ${target} için uygula`,
            'modals.bulkApply.applySortAndGroupTitle': (target: string) => `Sıralama ve gruplandırma ${target} için uygulansın mı?`,
            'modals.bulkApply.affectedCountMessage': (count: number) => `Değişecek mevcut geçersiz kılmalar: ${count}.`,
            'modals.navRainbowSection.title': (section: string) => `Gökkuşağı renkleri: ${section}`,
            'modals.folderSuggest.placeholder': (name: string) => `${name} öğesini klasöre taşı...`,
            'modals.folderSuggest.multipleFilesLabel': (count: number) => `${count} dosya`
        }
    },
    uk: {
        dateFormat: 'D MMM YYYY',
        timeFormat: 'HH:mm',
        defaultVaultProfileName: 'За замовчуванням',
        bootstrap: {
            downloading: 'Завантаження мов…',
            continueInEnglish: 'Продовжити англійською',
            downloadFailed: 'Не вдалося завантажити мови. Notebook Navigator використовує англійську.'
        },
        formatters: {
            'paneHeader.applySortAndGroupToDescendants': (target: string) => `Застосувати сортування та групування для ${target}`,
            'modals.bulkApply.applySortAndGroupTitle': (target: string) => `Застосувати сортування та групування для ${target}?`,
            'modals.bulkApply.affectedCountMessage': (count: number) => `Наявних перевизначень, які зміняться: ${count}.`,
            'modals.navRainbowSection.title': (section: string) => `Кольори веселки: ${section}`,
            'modals.folderSuggest.placeholder': (name: string) => `Перемістити ${name} до теки...`,
            'modals.folderSuggest.multipleFilesLabel': (count: number) =>
                `${count} ${count % 10 === 1 && count % 100 !== 11 ? 'файл' : count % 10 >= 2 && count % 10 <= 4 && (count % 100 < 12 || count % 100 > 14) ? 'файли' : 'файлів'}`
        }
    },
    vi: {
        dateFormat: 'D MMM YYYY',
        timeFormat: 'HH:mm',
        defaultVaultProfileName: 'Mặc định',
        bootstrap: {
            downloading: 'Đang tải ngôn ngữ…',
            continueInEnglish: 'Tiếp tục bằng tiếng Anh',
            downloadFailed: 'Không tải được ngôn ngữ. Notebook Navigator đang sử dụng tiếng Anh.'
        },
        formatters: {
            'paneHeader.applySortAndGroupToDescendants': (target: string) => `Áp dụng sắp xếp và nhóm cho ${target}`,
            'modals.bulkApply.applySortAndGroupTitle': (target: string) => `Áp dụng sắp xếp và nhóm cho ${target}?`,
            'modals.bulkApply.affectedCountMessage': (count: number) => `Ghi đè hiện có sẽ thay đổi: ${count}.`,
            'modals.navRainbowSection.title': (section: string) => `Màu cầu vồng: ${section}`,
            'modals.folderSuggest.placeholder': (name: string) => `Di chuyển ${name} đến thư mục...`,
            'modals.folderSuggest.multipleFilesLabel': (count: number) => `${count} tệp`
        }
    },
    zh_cn: {
        dateFormat: 'YYYY年M月D日',
        timeFormat: 'HH:mm',
        defaultVaultProfileName: '默认',
        bootstrap: {
            downloading: '正在下载语言…',
            continueInEnglish: '继续使用英语',
            downloadFailed: '语言下载失败。Notebook Navigator 正在使用英语。'
        },
        formatters: {
            'paneHeader.applySortAndGroupToDescendants': (target: string) => `将排序和分组应用到${target}`,
            'modals.bulkApply.applySortAndGroupTitle': (target: string) => `将排序和分组应用到${target}？`,
            'modals.bulkApply.affectedCountMessage': (count: number) => `将更改的现有覆盖：${count}。`,
            'modals.navRainbowSection.title': (section: string) => `彩虹颜色：${section}`,
            'modals.folderSuggest.placeholder': (name: string) => `将 ${name} 移动到文件夹...`,
            'modals.folderSuggest.multipleFilesLabel': (count: number) => `${count} 个文件`
        }
    },
    zh_tw: {
        dateFormat: 'YYYY年M月D日',
        timeFormat: 'HH:mm',
        defaultVaultProfileName: '預設',
        bootstrap: {
            downloading: '正在下載語言…',
            continueInEnglish: '繼續使用英語',
            downloadFailed: '語言下載失敗。Notebook Navigator 正在使用英語。'
        },
        formatters: {
            'paneHeader.applySortAndGroupToDescendants': (target: string) => `將排序與分組套用到${target}`,
            'modals.bulkApply.applySortAndGroupTitle': (target: string) => `將排序與分組套用到${target}？`,
            'modals.bulkApply.affectedCountMessage': (count: number) => `將更改的現有覆寫：${count}。`,
            'modals.navRainbowSection.title': (section: string) => `彩虹顏色: ${section}`,
            'modals.folderSuggest.placeholder': (name: string) => `將 ${name} 移動至資料夾...`,
            'modals.folderSuggest.multipleFilesLabel': (count: number) => `${count} 個檔案`
        }
    }
};
export type LanguageCode = keyof typeof LANGUAGE_METADATA;
